project:
  type: book
  # resources:

book:
  title: Probability and Random Signals II
  description: "Course Notes for ECSE 509 (McGill University)"
  site-url: "https://adityam.github.io/probability-and-random-signals/"

  repo-url: "https://github.com/adityam/probabiity-and-random-signals"
  repo-actions: [edit]
  repo-branch: quarto
  reader-mode: true

  navbar:
    background: dark
    title: false
    pinned: false
    search: false
    left:
    - href: index.html
      text: Probability and Random Signals II

  chapters:
      - index.qmd
      - probability-spaces.qmd
      - random-variables.qmd
      - conditional-expectation.qmd
      - moment-generating-functions.qmd
      - inequalities.qmd
      - convergence-of-random-variables.qmd
      - markov-chains.qmd

format:
  html:
    author:
      - name: Aditya Mahajan
        url: "https://adityam.github.io"
        affiliation: McGill University
        affiliation-url: "http://www.mcgill.ca/ece"
        # citation:
        #   type: webpage
        #   container-title: "Course notes for Probability and Random Signals"
        #     # google-scholar: true
    theme: 
      light: 
        - lumen
        - static/css/style.scss
      dark: 
        - darkly
        - static/css/style.scss
    mermaid:
      theme: neutral
    include-in-header: 
      - static/html/mathjax.html
      - static/html/clicky.html

    reference-location: margin
      #    citation-location: margin
    filters:
      - _extensions/schochastics/nutshell/nutshell.lua
    published-title: Updated
    date: last-modified
    notebook-links: inline

    embed-resources: false
    smooth-scroll: true
