---
course:
  term: "Fall 2025"
  office-hours: "Tuesday 10:00am–11:00am"
  teaching-assistants: "Ziqi Huang"
  mid-term: "Oct 8"
  lectures:
    - "8:35am–9:55am Monday, Wednesday (ENGTR 2100)"
  tutorials:
    - "12:35pm–1:25pm Friday, (ENGTR 2110)"
format: 
  html: 
    number-sections: false
---

# Course Outline {.unnumbered}

## General Information ({{< meta course.term >}})

Instructor
: -  Aditya Mahajan 
- *Office Hours*: {{< meta course.office-hours >}}

Teaching Assistants
: - {{< meta course.teaching-assistants >}} 

Lectures
: - {{< meta course.lectures >}} 

Tutorials
: - {{< meta course.tutorials >}} 

Prerequisites
: - ECSE 205 (Probability and Random Signals I)
- ECSE 206 or ECSE 316 (Signals and Systems)


Communication
: [Use the discussion board on myCourses]{.text-info} for all questions related to the course. Only personal emails related to medical exceptions for missing a deliverable will be answered.

<!--
## Graduate Attributes and Learning Outcomes

| Attribute | Description | Status |
|-----------|-------------|--------|
| KB | Knowledge Base for Engineering | Developed |
| PA | Problem Analysis | Developed |
| IN | Investigation | Developed |
| DE | Design | Introduced |

Upon the successful completion of this course, the student students will have demonstrated the ability to:

- Apply time- and frequency-domain tools to analyze linear time-invariant systems (KB, PA)
- Design controllers based on state-space methods and lead-lag compensators to meet time-response specifications (KB, PA, DE)
- Use Matlab to analyze and synthesize controllers for linear time-invariant systems (DE, IN)

-->

## Course Content

| Week | Material Covered | 
|------|:-----------------|
| 1    | [Probability spaces, algebra of events, axioms of probability](probability-spaces.qmd) |
| 2    | [Random variables and random vectors](random-variables.qmd) | 
| 3    | [Random variables and random vectors (continued)](random-variables.qmd) | 
| 4    | [Conditional probability and conditional expectation](conditional-expectation.qmd) |
| 5    | [Moment generating functions and sums of random variables](moment-generating-functions.qmd) |
| 6    | [Probability inequalities](inequalities.qmd) |
| 7    | Review and Mid-Term | 
| 8    | [Convergence of random variables and the strong law of large numbers](convergence-of-random-variables.qmd) | 
| 9    | [Markov chains](markov-chains.qmd) | 
| 10   | Markov chains (continued) | 
| 11   | [Poisson processes](poisson-processes.qmd) |
| 12   | Gaussian processes and minimum mean squared error estimation | 
| 13   | Wide sense stationary processes | 

: {tbl-colwidths="[10,90]" .striped}

<small>[The material for the lecture notes is taken from various sources including the textbook and the reference book, as well as the lecture notes of Prof. Ioannis Psaromiglikos (McGill) and Prof. Ashutosh Nayyar (USC).]{.text-muted}</small>

## Course Material

Textbook
: - Grimmett and Stirzaker, _Probability and Random Processes,_ 4th edition, Oxford University Press, 2020.


"Engineering" Graduate Probability textbooks

: - J.A. Gubner, _Probability and Random Processes for Electrical and Computer Engineers,_ Cambridge University Press, 2006.
- S.H. Chan, _Introduction to Probability for Data Science,_ Michigan Publishing, 2021.
- H. Hsu, _Probability, Random Variables, and Random Processes,_ McGraw Hill, 1997.

Exercise books

: - F. Mosteller, _Fifty challenging problems in probability with solutions,_ Courier Corporation, 1987. [Available online](https://archive.org/details/fiftychallenging00most)
- Grimmett and Stirzaker, _One Thousand Exercises in Probability,_ Oxford University Press, 2000. 


## Evaluation

- **Assignments (25%)** Weekly homework assignments. Typically, each assignment will consist of four or five questions, out of which [one or two randomly selected questions will be graded]{.text-danger}. 

- **Mid Term (25%)** Closed book in-class exam.
  [**{{< meta course.mid-term >}}**]{.text-danger} (during class time)

- **Final Exam (50%)** Closed book, in-person exam. Will be scheduled by the exam office and the dates will be announced later.

    The final exam will cover **all** the material seen in the class during the term.

## Marking policy

- Assignments must be submitted electronically on myCourses as a PDF. You may write the assignments on paper and then scan them as a PDF (there are several such apps available for all phone platforms), or write on a tablet and convert to PDF, or type using a word processor.

- **There will no make-up examination** for students who miss a mid-term.

  - Student who miss the exam due to a valid reason (see [Faculty of Engineering policy][policy]) should **notify the instructor within a week** of the exam and provide **necessary documentation**.

  - If, and only if, proper documentation for a missed exam is presented, the marks for the missed exam will be shifted to the final exam.

  - Students who miss the mid-term exam for any other reason (e.g., no medical note, going to the exam at the wrong time, or on the wrong day, etc.) will get zero marks on the exam.

- Any request for reevaluation of a mid-term or an assignment must be made **in writing within a week of its return**. Note that requesting a re-grade will mean that you **WHOLE** assignment or exam will be re-graded.


Right to submit in English or French written work that is to be graded.
: In accord with McGill University’s [Charter of Students’ Rights][charter], students in this course have the right to submit in English or in French any written work that is to be graded.

Academic Integrity
: McGill University values academic integrity. Therefore all students must understand the meaning and consequences of cheating, plagiarism and other academic offences under the [Code of Student Conduct and Disciplinary Procedures][code] (see McGill’s [guide to academic honesty][guide] for more information).

    L’université McGill attache une haute importance à l’honnêteté académique. Il incombe par conséquent à tous les étudiants de comprendre ce que l’on entend par tricherie, plagiat et autres infractions académiques, ainsi que les conséquences que peuvent avoir de telles actions, selon le [Code de conduite de l’étudiant et des procédures disciplinaires][code] (pour de plus amples renseignements, veuillez consulter le [guide pour l’honnêteté académique][guide] de McGill.)

## Course delivery

The course is taught in a “chalk and board” style; there will be no power point presentations. All students are expected to attend lectures and take notes. Partial notes on some of the material will be provided, but are not a substitute for the material covered in class.

© Instructor-generated course materials (e.g., handouts, notes, summaries, exam questions) are protected by law and may not be copied or distributed in any form or in any medium without explicit permission of the instructor. Note that infringements of copyright can be subject to follow up by the University under the Code of Student Conduct and Disciplinary Procedures.

## Additional Notes

- As the instructor of this course I endeavor to provide an inclusive learning environment. However, if you experience barriers to learning in this course, do not hesitate to discuss them with me or contact the office of [Student Accessibility and Achievement][OSD].

- [End-of-course evaluations][evaluations] are one of the ways that McGill works towards maintaining and improving the quality of courses and the student’s learning experience. You will be notified by e-mail when the evaluations are available. Please note that a minimum number of responses must be received for results to be available to students.


[policy]: https://www.mcgill.ca/engineering/students/undergraduate/courses-registration/exams-assessment/midterms-and-class-tests/adjustments-missed-midterms-and-class-tests

[charter]: https://www.mcgill.ca/secretariat/files/secretariat/charter_of_student_rights_last_approved_october_262017.pdf

[code]: https://www.mcgill.ca/secretariat/files/secretariat/code_of_student_conduct_and_disciplinary_procedures.pdf

[guide]: http://www.mcgill.ca/students/srr/honest/

[evaluations]: http://www.mcgill.ca/mercury/

[OSD]: https://www.mcgill.ca/access-achieve/

